modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"
[[mods]]
modId="hydrogenmod"
version="1.0.0"
displayName="HydrogenMod"
logoFile="hydrogenmod.png"
credits=""
authors="stouma915"
description="水素で遊ぼう"
[[dependencies.hydrogenmod]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.hydrogenmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
